const fs = require('fs');
const L = '\n';
let out = '';
function W(s){ out += s + L; }
W('');
W('<script setup>');
W('import { ref, computed } from \'vue\'');
W('import { ArrowLeft, Edit } from \'@element-plus/icons-vue\'');
W('import { ElMessage } from \'element-plus\'');
W('import { useDueDiligenceStore } from \'../stores/dueDiligence.js\'');
W('import { useDiagnosisStore } from \'../stores/enterpriseDiagnosis.js\'');
W('import { enterpriseDB } from \'../data/mockEnterpriseDiagnosis.js\'');
W('import { riskItems, artifactsList } from \'../data/mockDueDiligence.js\'');
W('import { getDiagnosisMock } from \'../data/mockEnterpriseDiagnosis.js\'');
W('const dueDiligenceStore = useDueDiligenceStore()');
W('const diagnosisStore = useDiagnosisStore()');
W('const view = ref(\'list\')');
W('const tpl = ref(\'\')');
W('const ent = ref(null)');
W('const entText = ref(\'\')');
W('const entList = ref([])');
W('const showEntDrop = ref(false)');
W('const dsOn = ref([])');
W('const creating = ref(false)');
W('const rptName = ref(\'\')');
W('const secs = ref([])');
W('const editId = ref(\'\')');
W('const editText = ref(\'\')');
W('const msgs = ref([])');
W('const chText = ref(\'\')');
W('const chBusy = ref(false)');
W('const dsItems = [');
W('  { id: \'biz\', name: \'工商查询\', st: \'ready\' },');
W('  { id: \'due\', name: \'尽调资料\', st: \'ready\' },');
W('  { id: \'diag\', name: \'企业诊断\', st: \'ready\' },');
W('  { id: \'mon\', name: \'企业监测\', st: \'ready\' },');
W('  { id: \'tax\', name: \'税票数据\', st: \'partial\' },');
W(']');
W('const quicks = [\'展开风险分析\', \'语气正式一点\', \'加税票数据\', \'总结一下\', \'证据链交叉比对\', \'导出Word\']');
W('const dueReportList = computed(() => {');
W('  return dueDiligenceStore.tasks.filter(t => t.progress >= 80).map((t, idx) => ({');
W('    id: t.id,');
W('    name: `${t.name} - 尽调报告${t.status?.includes(\'待确认\') ? \'\' : \'（草稿）\'}`,');
W('    status: t.status?.includes(\'待确认\') ? \'completed\' : \'draft\',');
W('    progress: t.progress,');
W('    createdAt: `2026-06-${String(28-idx).padStart(2,\'0\')} 14:30`,');
W('    tpl: \'due\',');
W('    creditCode: t.creditCode || \'—\',');
W('  }))');
W('})');
W('const diagReportList = computed(() => {');
W('  const diagnosed = diagnosisStore.diagnosisHistory || []');
W('  return diagnosed.map((d, idx) => ({');
W('    id: \'DIAG_\'+d.enterprise,');
W('    name: `${d.enterprise} - 诊断报告`,');
W('    status: \'completed\', progress: 100,');
W('    createdAt: `2026-06-${String(27-idx).padStart(2,\'0\')} ${String(10+idx).padStart(2,\'0\')}:15`,');
W('    tpl: \'diag\',');
W('    creditCode: enterpriseDB.find(e=>e.name===d.enterprise)?.creditCode || \'—\',');
W('  }))');
W('})');
W('const reportList = computed(() => [...dueReportList.value, ...diagReportList.value].sort((a,b) => b.createdAt.localeCompare(a.createdAt)))');
W('const enterprisePool = computed(() => {');
W('  const map = {}');
W('  dueDiligenceStore.tasks.forEach(t => { if(t.name && t.creditCode) map[t.creditCode] = {n:t.name, c:t.creditCode} })');
W('  enterpriseDB.forEach(e => { if(!map[e.creditCode]) map[e.creditCode] = {n:e.name, c:e.creditCode} })');
W('  return Object.keys(map).map(k => map[k])');
W('})');
W('function onEntInput(){const t=entText.value.trim(); if(t.length>=1) entList.value=enterprisePool.value.filter(e=>e.n.indexOf(t)>=0||e.c.indexOf(t)>=0); else entList.value=[]}');
W('function pickEnt(e){ent.value=e;entText.value=e.n;entList.value=[];showEntDrop.value=false}');
W('function hideEntDrop(){setTimeout(()=>{showEntDrop.value=false},200)}');
W('function startCreate(){view.value=\'create\';tpl.value=\'\';ent.value=null;entText.value=\'\';entList.value=[];dsOn.value=[]}');
W('function toggleDs(id){const i=dsOn.value.indexOf(id);if(i>=0)dsOn.value.splice(i,1);else dsOn.value.push(id)}');
fs.writeFileSync('D:\\demo\\ai-copilot\\_part2.txt', out);
console.log('Part 2 written, length:', out.length);