const fs = require('fs');
const L = '\n';
let out = '';
function W(s){ out += s + L; }
W('<template>');
W('  <div class="page">');
W('    <div class="page-header">');
W('      <h1 class="page-title">智能报告</h1>');
W('      <p class="page-subtitle">AI 驱动的文档工作台</p>');
W('    </div>');
W('    <div v-if="view === \'list\'" class="card-animate">');
W('      <div class="create-entry" @click="startCreate()">');
W('        <div class="create-icon">✨</div><div>');
W('          <div class="create-title">新建报告</div>');
W('          <div class="create-desc">选择模板和数据源，AI 自动生成初稿</div>');
W('        </div></div>');
W('      <div class="history-title">最近报告</div>');
W('      <div v-if="reportList.length === 0" class="empty-hint">暂无可生成的报告，请先推进尽调或诊断任务至 80% 以上。</div>');
W('      <div v-for="(item, idx) in reportList" :key="item.id" class="report-card" @click="openReport(idx)">');
W('        <div class="rc-icon">{{ item.tpl === \'due\' ? \'📋\' : item.tpl === \'diag\' ? \'🔍\' : \'🌐\' }}</div>');
W('        <div><div class="rc-name">{{ item.name }}</div>');
W('          <div class="rc-meta">');
W('            <span class="rc-tag" :class="item.status === \'completed\' ? \'done\' : \'draft\'">{{ item.status === \'completed\' ? \'已完成\' : \'草稿\' }}</span>');
W('            <span class="rc-time">{{ item.createdAt }}</span>');
W('            <span class="rc-credit">{{ item.creditCode }}</span>');
W('            <span class="rc-progress">进度 {{ item.progress }}%</span>');
W('          </div></div></div>');
W('    </div>');
W('    <div v-if="view === \'create\' && !creating" class="card-animate">');
W('      <div class="step-bar"><el-icon class="back" @click="view=\'list\'"><ArrowLeft /></el-icon><span class="step-t">新建报告</span></div>');
W('      <div class="fg"><label class="fl">选择报告模板</label>');
W('        <div class="tpl-row">');
W('          <div class="tpl-card" :class="{ on: tpl===\'due\' }" @click="tpl=\'due\'"><div class="tpl-i">📋</div><div class="tpl-n">尽调报告</div><div class="tpl-d">基于尽调资料生成标准尽调报告</div></div>');
W('          <div class="tpl-card" :class="{ on: tpl===\'diag\' }" @click="tpl=\'diag\'"><div class="tpl-i">🔍</div><div class="tpl-n">诊断报告</div><div class="tpl-d">基于企业诊断结果生成诊断摘要</div></div>');
W('          <div class="tpl-card" :class="{ on: tpl===\'pan\' }" @click="tpl=\'pan\'"><div class="tpl-i">🌐</div><div class="tpl-n">全景报告</div><div class="tpl-d">汇总企业多维度数据生成全景视图</div></div>');
W('        </div></div>');
W('      <div class="fg" v-if="tpl"><label class="fl">选择企业</label>');
W('        <div class="ent-w"><input v-model="entText" class="ent-in" placeholder="输入企业名称或信用代码" @input="onEntInput()" @focus="showEntDrop=true" @blur="hideEntDrop()" />');
W('          <div v-if="showEntDrop && entList.length" class="ent-drop">');
W('            <div v-for="e in entList" :key="e.c" class="ent-opt" @mousedown="pickEnt(e)"><span>{{ e.n }}</span><span class="ent-oc">{{ e.c }}</span></div>');
W('          </div></div>');
W('        <div v-if="ent" class="ent-ok"><span style="color:#10b981">✓ 已选择：{{ ent.n }}</span></div></div>');
W('      <div class="fg" v-if="ent"><label class="fl">选择数据源</label>');
W('        <div class="ds-row">');
W('          <div v-for="ds in dsItems" :key="ds.id" class="ds-card" :class="{ on: dsOn.includes(ds.id) }" @click="toggleDs(ds.id)"><div class="ds-n">{{ ds.name }}</div><div class="ds-s" :class="ds.st">{{ ds.st === \'ready\' ? \'可用\' : \'部分可用\' }}</div></div>');
W('        </div></div>');
W('      <div v-if="tpl && ent" class="gen-wrap"><el-button type="primary" size="large" :disabled="dsOn.length===0" @click="doGen()">生成报告（{{ dsOn.length }} 个数据源）</el-button></div>');
W('    </div>');
W('    <div v-if="view === \'create\' && creating" class="card-animate">');
W('      <div class="gen-box"><div class="gen-spin"></div><div class="gen-t">正在生成报告...</div>');
W('        <div class="gen-steps"><div class="gs done">✓ 读取数据源</div><div class="gs done">✓ 分析数据结构</div><div class="gs active">⟳ 生成报告内容</div><div class="gs">○ 排版与格式化</div></div>');
W('      </div></div>');
W('    <div v-if="view === \'editor\'" class="card-animate">');
W('      <div class="ed-top"><el-icon class="back" @click="view=\'list\'"><ArrowLeft /></el-icon><div class="ed-t">{{ rptName }}</div>');
W('        <div class="ed-btns"><el-button size="small" type="primary" @click="elMsg(\'已导出 Word\')">导出 Word</el-button></div></div>');
W('      <div class="ed-body"><div class="ed-left">');
W('        <div v-for="(sec, idx) in secs" :key="sec.id" class="sec-card">');
W('          <div class="sec-head"><div class="sec-num">{{ idx + 1 }}</div><div class="sec-title">{{ sec.title }}</div><el-icon class="sec-edit" @click="doEdit(sec.id)"><Edit /></el-icon></div>');
W('          <textarea v-if="editId === sec.id" v-model="editText" class="sec-ta" rows="6"></textarea>');
W('          <div v-else class="sec-body" @dblclick="doEdit(sec.id)">{{ sec.text }}</div>');
W('          <div v-if="editId === sec.id" class="sec-act"><el-button size="small" @click="editId=\'\'">取消</el-button><el-button size="small" type="primary" @click="doSave()">保存</el-button></div>');
W('        </div></div>');
W('        <div class="ed-right"><div class="ch-head">对话式修改</div>');
W('          <div class="ch-msgs">');
W('            <div v-for="(m, i) in msgs" :key="i" class="ch-m" :class="m.role"><span class="ch-av">{{ m.role === \'ai\' ? \'🤖\' : \'👤\' }}</span><div class="ch-bubble" v-html="md(m.text)"></div></div>');
W('            <div v-if="chBusy" class="ch-m ai"><span class="ch-av">🤖</span><div class="ch-bubble ch-think">思考中...</div></div>');
W('          </div>');
W('          <div class="ch-input-row"><input v-model="chText" class="ch-input" placeholder="说你想怎么改..." @keyup.enter="doSend()" /><el-button size="small" type="primary" :disabled="!chText || chBusy" @click="doSend()">发送</el-button></div>');
W('          <div class="ch-quick"><span class="ch-ql">快捷：</span><span v-for="q in quicks" :key="q" class="ch-q" @click="quickCmd(q)">{{ q }}</span></div>');
W('        </div></div>');
W('    </div>');
W('  </div>');
W('</template>');
fs.writeFileSync('D:\\demo\\ai-copilot\\_part1.txt', out);
console.log('Part 1 written, length:', out.length);